//! Build-only наблюдение фиксированного Git source artifact; runtime не читает workspace.

use std::collections::BTreeMap;
use std::env;
use std::ffi::{OsStr, OsString};
use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

const SOURCE_PATH: &str = "crates/labcolors-core";
const OUTPUT: &str = "certificate-source-tree-v1.bin";

#[derive(Debug)]
pub struct Unavailable;

type Result<T> = std::result::Result<T, Unavailable>;

pub fn generate() -> Result<()> {
    println!("cargo:rerun-if-changed=.");
    println!("cargo:rerun-if-env-changed=PATH");
    println!("cargo:rerun-if-env-changed=GIT_EXEC_PATH");
    let manifest = env::var_os("CARGO_MANIFEST_DIR").ok_or(Unavailable)?;
    let manifest = PathBuf::from(manifest);
    let out = PathBuf::from(env::var_os("OUT_DIR").ok_or(Unavailable)?);
    // Generated bytes не должны стать входом идентифицируемого subtree.
    let out = fs::canonicalize(out).map_err(|_| Unavailable)?;
    let descriptor = if out.starts_with(fs::canonicalize(&manifest).map_err(|_| Unavailable)?) {
        // Standalone archive с обычным target внутри crate остаётся собираемым.
        // Self-input лишает source identity, но не делает output недоступным.
        None
    } else {
        descriptor(&manifest).ok()
    };
    replace_output(&out, descriptor.as_ref().map_or(&[], |bytes| &bytes[..]))
}

fn descriptor(manifest: &Path) -> Result<[u8; 47]> {
    let manifest = fs::canonicalize(manifest).map_err(|_| Unavailable)?;
    if env::var("CARGO_PKG_NAME").as_deref() != Ok("labcolors-core")
        || manifest.file_name() != Some(OsStr::new("labcolors-core"))
        || manifest.parent().and_then(Path::file_name) != Some(OsStr::new("crates"))
    {
        return Err(Unavailable);
    }
    let expected_root = manifest
        .parent()
        .and_then(Path::parent)
        .ok_or(Unavailable)?;
    // Отсутствующая .git — реальный обязательный input: его появление тоже
    // должно запустить проверку. Отдельного always-rebuild sentinel нет.
    watch_metadata_boundary(&expected_root.join(".git"))?;
    let git = Git { cwd: &manifest };
    let before = git.observe()?;
    if manifest != before.root.join(SOURCE_PATH) || before.root != expected_root {
        return Err(Unavailable);
    }
    verify_directory(&git, &manifest, &before.tree)?;
    if git.observe()? != before {
        return Err(Unavailable);
    }
    // Сборка предполагает isolated checkout без concurrent source writer.
    // Проверка Git до/после не является атомарным snapshot файловой системы.
    let mut bytes = [0_u8; 47];
    bytes[..7].copy_from_slice(b"LCST\x00\x01\x01");
    bytes[7..].copy_from_slice(before.tree.as_bytes());
    Ok(bytes)
}

#[derive(PartialEq, Eq)]
struct Observation {
    root: PathBuf,
    git_dir: PathBuf,
    common_dir: PathBuf,
    tree: String,
}

struct Git<'a> {
    cwd: &'a Path,
}

impl Git<'_> {
    fn read(&self, args: &[&str]) -> Result<Vec<u8>> {
        let mut command = Command::new("git");
        command
            .arg("--no-replace-objects")
            .arg("--no-lazy-fetch")
            .args(args)
            .current_dir(self.cwd)
            .stdin(Stdio::null())
            .stderr(Stdio::null());
        // Caller environment не выбирает другой repository/index/object store.
        // GIT_EXEC_PATH принадлежит установленному host Git, не source identity.
        for (name, _) in env::vars_os() {
            if name.to_string_lossy().starts_with("GIT_") && name != "GIT_EXEC_PATH" {
                command.env_remove(name);
            }
        }
        let output = command
            .env("GIT_OPTIONAL_LOCKS", "0")
            .env("GIT_NO_LAZY_FETCH", "1")
            .env("GIT_TERMINAL_PROMPT", "0")
            .output()
            .map_err(|_| Unavailable)?;
        if !output.status.success() {
            return Err(Unavailable);
        }
        Ok(output.stdout)
    }

    fn path(&self, args: &[&str]) -> Result<PathBuf> {
        let output = self.read(args)?;
        let path = PathBuf::from(os_string(line(&output)?)?);
        if !path.is_absolute() {
            return Err(Unavailable);
        }
        fs::canonicalize(path).map_err(|_| Unavailable)
    }

    fn observe(&self) -> Result<Observation> {
        let root = self.path(&["rev-parse", "--show-toplevel"])?;
        let git_dir = self.path(&["rev-parse", "--absolute-git-dir"])?;
        let common_dir = self.path(&["rev-parse", "--path-format=absolute", "--git-common-dir"])?;
        // Cargo рекурсивно наблюдает directories: HEAD/index, refs, config,
        // objects. Watches нужны и при отказе ниже из-за missing object/HEAD.
        watch(&git_dir)?;
        watch(&common_dir)?;
        if self.read(&["rev-parse", "--show-object-format"])? != b"sha1\n" {
            return Err(Unavailable);
        }
        let output = self.read(&["rev-parse", "--verify", "HEAD:crates/labcolors-core"])?;
        let tree = object_id(line(&output)?)?;
        if self.read(&["cat-file", "-t", &tree])? != b"tree\n" {
            return Err(Unavailable);
        }
        Ok(Observation {
            root,
            git_dir,
            common_dir,
            tree,
        })
    }
}

struct Entry {
    mode: String,
    object: String,
}

fn verify_directory(git: &Git<'_>, path: &Path, tree: &str) -> Result<()> {
    if !fs::symlink_metadata(path)
        .map_err(|_| Unavailable)?
        .is_dir()
    {
        return Err(Unavailable);
    }
    let listing = git.read(&["ls-tree", "--full-tree", "-z", tree])?;
    let mut entries = BTreeMap::new();
    if !listing.is_empty() && !listing.ends_with(&[0]) {
        return Err(Unavailable);
    }
    for record in listing.split_inclusive(|byte| *byte == 0) {
        let record = record.strip_suffix(&[0]).ok_or(Unavailable)?;
        let tab = record
            .iter()
            .position(|byte| *byte == b'\t')
            .ok_or(Unavailable)?;
        let mut header = record[..tab].split(|byte| *byte == b' ');
        let mode = header.next().ok_or(Unavailable)?;
        let kind = header.next().ok_or(Unavailable)?;
        let object = object_id(header.next().ok_or(Unavailable)?)?;
        if header.next().is_some()
            || !matches!(
                (mode, kind),
                (b"040000", b"tree") | (b"100644" | b"100755" | b"120000", b"blob")
            )
        {
            return Err(Unavailable);
        }
        let name = &record[tab + 1..];
        if name.is_empty() || name == b"." || name == b".." || name.contains(&b'/') {
            return Err(Unavailable);
        }
        #[cfg(not(unix))]
        if name.contains(&b'\\') {
            return Err(Unavailable);
        }
        let entry = Entry {
            mode: String::from_utf8(mode.to_vec()).map_err(|_| Unavailable)?,
            object,
        };
        if entries.insert(os_string(name)?, entry).is_some() {
            return Err(Unavailable);
        }
    }
    for physical in fs::read_dir(path).map_err(|_| Unavailable)? {
        let physical = physical.map_err(|_| Unavailable)?;
        let entry = entries.remove(&physical.file_name()).ok_or(Unavailable)?;
        let path = physical.path();
        let kind = fs::symlink_metadata(&path)
            .map_err(|_| Unavailable)?
            .file_type();
        match entry.mode.as_str() {
            "040000" if kind.is_dir() => verify_directory(git, &path, &entry.object)?,
            "100644" | "100755" if kind.is_file() => {
                // Git mode остаётся в T. Physical exec bit не меняет source bytes.
                let bytes = fs::read(path).map_err(|_| Unavailable)?;
                if bytes != git.read(&["cat-file", "blob", &entry.object])? {
                    return Err(Unavailable);
                }
            }
            "120000" if kind.is_symlink() => {
                // Не следуем по ссылке: artifact содержит literal target, не его content.
                let target = fs::read_link(path).map_err(|_| Unavailable)?;
                if os_bytes(target.as_os_str())?
                    != git.read(&["cat-file", "blob", &entry.object])?
                {
                    return Err(Unavailable);
                }
            }
            _ => return Err(Unavailable),
        }
    }
    if !entries.is_empty() {
        return Err(Unavailable);
    }
    Ok(())
}

fn object_id(bytes: &[u8]) -> Result<String> {
    if bytes.len() != 40
        || !bytes
            .iter()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(b))
    {
        return Err(Unavailable);
    }
    String::from_utf8(bytes.to_vec()).map_err(|_| Unavailable)
}

fn line(bytes: &[u8]) -> Result<&[u8]> {
    bytes
        .strip_suffix(b"\n")
        .filter(|line| !line.contains(&b'\n') && !line.contains(&b'\r'))
        .ok_or(Unavailable)
}

fn watch(path: &Path) -> Result<()> {
    let text = path
        .to_str()
        .filter(|text| !text.contains(['\n', '\r']))
        .ok_or(Unavailable)?;
    println!("cargo:rerun-if-changed={text}");
    Ok(())
}

fn watch_metadata_boundary(dot_git: &Path) -> Result<()> {
    watch_metadata_input(dot_git)?;
    let Ok(bytes) = fs::read(dot_git) else {
        return Ok(());
    };
    let Some(target) = bytes.strip_prefix(b"gitdir: ") else {
        return Ok(());
    };
    let target = PathBuf::from(os_string(line(target)?)?);
    let git_dir = dot_git.parent().ok_or(Unavailable)?.join(target);
    watch_metadata_input(&git_dir)?;
    if let Ok(bytes) = fs::read(git_dir.join("commondir")) {
        let common = PathBuf::from(os_string(line(&bytes)?)?);
        watch_metadata_input(&git_dir.join(common))?;
    }
    // Это только invalidation для broken/missing linked metadata. Identity
    // всё равно требует successful Git lookup, никакого filesystem fallback ID.
    Ok(())
}

fn watch_metadata_input(path: &Path) -> Result<()> {
    watch(path)?;
    let mut existing = path;
    while !existing.try_exists().map_err(|_| Unavailable)? {
        existing = existing.parent().ok_or(Unavailable)?;
    }
    // Возврат metadata через rename сохраняет старый mtime самого input.
    // Пока он отсутствует, изменение существующего parent запускает проверку.
    // После восстановления этот расширенный watch больше не нужен.
    if existing != path {
        watch(existing)?;
    }
    Ok(())
}

#[cfg(unix)]
fn os_string(bytes: &[u8]) -> Result<OsString> {
    use std::os::unix::ffi::OsStringExt;
    Ok(OsString::from_vec(bytes.to_vec()))
}

#[cfg(not(unix))]
fn os_string(bytes: &[u8]) -> Result<OsString> {
    String::from_utf8(bytes.to_vec())
        .map(OsString::from)
        .map_err(|_| Unavailable)
}

#[cfg(unix)]
fn os_bytes(text: &OsStr) -> Result<Vec<u8>> {
    use std::os::unix::ffi::OsStrExt;
    Ok(text.as_bytes().to_vec())
}

#[cfg(not(unix))]
fn os_bytes(text: &OsStr) -> Result<Vec<u8>> {
    text.to_str()
        .map(|text| text.as_bytes().to_vec())
        .ok_or(Unavailable)
}

fn replace_output(out: &Path, bytes: &[u8]) -> Result<()> {
    let path = out.join(OUTPUT);
    if fs::read(&path).ok().as_deref() == Some(bytes) {
        return Ok(());
    }
    let temporary = out.join(format!("{OUTPUT}.{}.tmp", std::process::id()));
    let result = (|| {
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)?;
        file.write_all(bytes)?;
        file.sync_all()?;
        drop(file);
        fs::rename(&temporary, path)
    })();
    if result.is_err() {
        let _ = fs::remove_file(temporary);
    }
    result.map_err(|_| Unavailable)
}
