use labcolors_core::neutral::{CurveParams, NeutralCurve};
use labcolors_core::scale::AccentCurve;
use labcolors_core::ViewingConditions;
use std::fs;

const BAR_W: u32 = 400;
const BAR_H: u32 = 40;
const MARGIN: u32 = 40;
const COL_GAP: u32 = 48;
const SAMPLES: u32 = 400;

fn sample_steps(curve: &impl labcolors_core::ColorCurve) -> Vec<String> {
    (0..SAMPLES)
        .map(|i| curve.at(i as f64 / (SAMPLES - 1) as f64).to_hex())
        .collect()
}

fn hex_at(t: f64, colors: &[String]) -> &str {
    let idx = (t * (colors.len() - 1) as f64).round() as usize;
    &colors[idx.min(colors.len() - 1)]
}

fn main() {
    let light = NeutralCurve::new("#FFFFFF", "#787880", "#101012").unwrap();
    let dim = NeutralCurve::with_vc(
        "#FFFFFF",
        "#787880",
        "#101012",
        &CurveParams::default(),
        &ViewingConditions::dim_surround(),
    )
    .unwrap();

    let curves: Vec<(&str, Vec<String>, Vec<String>)> = vec![
        ("Neutral", sample_steps(&light), sample_steps(&dim)),
        (
            "Blue (#007AFF)",
            sample_steps(&AccentCurve::new("#007AFF", &light).unwrap()),
            sample_steps(&AccentCurve::new("#007AFF", &dim).unwrap()),
        ),
        (
            "Green (#34C759)",
            sample_steps(&AccentCurve::new("#34C759", &light).unwrap()),
            sample_steps(&AccentCurve::new("#34C759", &dim).unwrap()),
        ),
        (
            "Orange (#FF9500)",
            sample_steps(&AccentCurve::new("#FF9500", &light).unwrap()),
            sample_steps(&AccentCurve::new("#FF9500", &dim).unwrap()),
        ),
    ];

    let total_w = MARGIN * 2 + BAR_W * 2 + COL_GAP;
    let row_h = BAR_H + 32;
    let total_h = MARGIN * 2 + curves.len() as u32 * row_h;

    let mut s = String::new();
    s.push_str(&format!(
        r##"<svg xmlns='http://www.w3.org/2000/svg' width='{}' height='{}'>
<style>text{{font-family:system-ui,-apple-system,sans-serif}}</style>
<rect width='100%' height='100%' fill='{}'/>
<text x='{}' y='{}' font-size='18' font-weight='600' fill='{}'>Palettes</text>
<text x='{}' y='{}' font-size='11' fill='{}'>Light</text>
<text x='{}' y='{}' font-size='11' fill='{}'>Dim (dark theme)</text>
"##,
        total_w, total_h,
        "#ffffff",
        MARGIN, MARGIN - 8, "#1a1a1a",
        MARGIN, MARGIN + 10, "#999",
        MARGIN + BAR_W + COL_GAP, MARGIN + 10, "#999",
    ));

    let labels: [(f64, &str); 5] = [
        (0.0, "white"),
        (0.25, "light"),
        (0.5, "base"),
        (0.75, "dark"),
        (1.0, "black"),
    ];

    for (row_idx, (name, light_c, dim_c)) in curves.iter().enumerate() {
        let y = MARGIN + 30 + row_idx as u32 * row_h;
        let is_first = row_idx == 0;

        s.push_str(&format!(
            "<text x='{}' y='{}' font-size='12' fill='{}'>{}</text>\n",
            MARGIN, y - 4, "#666", name
        ));

        // Light bar
        let bx = MARGIN;
        s.push_str(&format!(
            "<rect x='{}' y='{}' width='{}' height='{}' fill='none' stroke='{}' stroke-width='0.5'/>\n",
            bx, y, BAR_W, BAR_H, "#ddd"
        ));
        for (i, col) in light_c.iter().enumerate() {
            s.push_str(&format!(
                "<rect x='{}' y='{}' width='1' height='{}' fill='{}'/>\n",
                bx + i as u32, y, BAR_H, col
            ));
        }

        // Dim bar
        let bx2 = MARGIN + BAR_W + COL_GAP;
        s.push_str(&format!(
            "<rect x='{}' y='{}' width='{}' height='{}' fill='none' stroke='{}' stroke-width='0.5'/>\n",
            bx2, y, BAR_W, BAR_H, "#ddd"
        ));
        for (i, col) in dim_c.iter().enumerate() {
            s.push_str(&format!(
                "<rect x='{}' y='{}' width='1' height='{}' fill='{}'/>\n",
                bx2 + i as u32, y, BAR_H, col
            ));
        }

        // Labels under neutral (row 0)
        if is_first {
            for &(t, _desc) in &labels {
                let px = bx + (t * (BAR_W - 1) as f64) as u32;
                let h = hex_at(t, light_c);
                s.push_str(&format!(
                    "<text x='{}' y='{}' font-size='9' fill='{}' text-anchor='middle'>{}</text>\n",
                    px, y + BAR_H + 12, "#aaa", h.to_lowercase()
                ));
            }
        }
    }

    s.push_str(&format!(
        "<text x='{}' y='{}' font-size='10' fill='{}'>generated by labcolors-preview</text>\n",
        MARGIN, total_h - 12, "#bbb"
    ));

    s.push_str("</svg>\n");

    fs::write("docs/palette.svg", &s).expect("write palette.svg");
    eprintln!("Written docs/palette.svg ({} bytes)", s.len());
}
