#!/usr/bin/env python3
"""Verify current applicability of the immutable feasibility benchmark.

The admitted Slice-A artifact keeps the exact measured ``Cargo.lock`` blob as
historical provenance.  This verifier deliberately does not reinterpret that
blob as a byte-for-byte constraint on unrelated workspace packages.  Instead
it proves that every current Core/benchmark subject is unchanged and that the
current lock preserves the exact ``labcolors-core`` record plus every sourced
registry/git package from the measured lock.  Only source-less non-Core
workspace records may differ.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import subprocess
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ARTIFACT = ROOT / (
    "crates/labcolors-core/contracts/"
    "wcag22-feasibility-benchmark-v1.json"
)
HISTORICAL_ONLY_PATH = "Cargo.lock"
EXPECTED_SUBJECT_PATHS = (
    "Cargo.toml",
    "crates/labcolors-core/src/lib.rs",
    "crates/labcolors-core/src/wcag22_feasibility.rs",
    "crates/labcolors-core/src/srgb8.rs",
    "crates/labcolors-core/src/sha256.rs",
    "crates/labcolors-core/src/wcag22.rs",
    "crates/labcolors-core/src/wcag22/kernel.rs",
    "crates/labcolors-core/src/wcag22/q55_data.rs",
    "crates/labcolors-core/src/wcag22_evidence.rs",
    "crates/labcolors-core/src/numerics.rs",
    "crates/labcolors-core/contracts/wcag22-srgb8-v1.json",
    "crates/labcolors-core/contracts/wcag22-srgb8-q55-proof-v1.json",
    "crates/labcolors-core/Cargo.toml",
    HISTORICAL_ONLY_PATH,
    "crates/labcolors-core/benches/wcag22_feasibility_admission.rs",
    "scripts/check_wcag22_feasibility_benchmark.py",
)
HEX_256 = re.compile(r"[0-9a-f]{64}")
GIT_OBJECT = re.compile(r"[0-9a-f]{40}")
FIELD = re.compile(r'^([a-zA-Z][a-zA-Z0-9_-]*) = "([^"]*)"$', re.MULTILINE)


class ApplicabilityError(ValueError):
    """One exact applicability law failed."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ApplicabilityError(message)


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def git_blob(object_id: str) -> bytes:
    require(GIT_OBJECT.fullmatch(object_id) is not None,
            "historical Cargo.lock Git object is invalid")
    result = subprocess.run(
        ["git", "cat-file", "blob", object_id],
        cwd=ROOT,
        check=False,
        capture_output=True,
    )
    require(result.returncode == 0,
            "historical Cargo.lock Git object is unavailable")
    return result.stdout


def package_blocks(lock: bytes, label: str) -> dict[tuple[str, str, str], bytes]:
    try:
        text = lock.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ApplicabilityError(f"{label} is not UTF-8") from error
    require(text.startswith(
        "# This file is automatically @generated by Cargo.\n"
        "# It is not intended for manual editing.\n"
        "version = 4\n"
    ), f"{label} is not canonical Cargo lockfile v4")
    parts = text.split("\n[[package]]\n")
    require(len(parts) > 1, f"{label} contains no package records")
    records: dict[tuple[str, str, str], bytes] = {}
    for index, raw in enumerate(parts[1:]):
        block = f"[[package]]\n{raw.rstrip()}\n".encode()
        fields = dict(FIELD.findall(raw))
        name = fields.get("name")
        version = fields.get("version")
        source = fields.get("source", "")
        require(bool(name) and bool(version),
                f"{label} package record {index} lacks name/version")
        key = (name, version, source)
        require(key not in records, f"{label} contains duplicate package identity {key}")
        records[key] = block
    return records


def check_lock_compatibility(historical: bytes, current: bytes) -> int:
    historical_records = package_blocks(historical, "historical Cargo.lock")
    current_records = package_blocks(current, "current Cargo.lock")
    core_keys = [key for key in historical_records if key[0] == "labcolors-core"]
    require(len(core_keys) == 1, "historical lock must contain one labcolors-core record")
    core_key = core_keys[0]
    require(current_records.get(core_key) == historical_records[core_key],
            "current Cargo.lock changed the exact labcolors-core dependency record")

    historical_sourced = {
        key: block for key, block in historical_records.items() if key[2]
    }
    current_sourced = {
        key: block for key, block in current_records.items() if key[2]
    }
    require(set(current_sourced) == set(historical_sourced),
            "current Cargo.lock changed the sourced package identity set")
    for key, block in historical_sourced.items():
        require(current_sourced[key] == block,
                f"current Cargo.lock changed sourced package record {key}")

    return sum(
        1
        for key in set(historical_records) | set(current_records)
        if not key[2]
        and key[0] != "labcolors-core"
        and historical_records.get(key) != current_records.get(key)
    )


def subject_manifest(payload: dict[str, Any]) -> dict[str, str]:
    raw = payload.get("subjectManifest")
    require(isinstance(raw, list) and len(raw) == len(EXPECTED_SUBJECT_PATHS),
            "subjectManifest must retain the exact measured path set")
    manifest: dict[str, str] = {}
    for index, expected_path in enumerate(EXPECTED_SUBJECT_PATHS):
        entry = raw[index]
        require(isinstance(entry, dict) and set(entry) == {"path", "sha256"},
                f"subjectManifest[{index}] has unexpected fields")
        require(entry.get("path") == expected_path,
                f"subjectManifest[{index}] path/order drifted")
        digest = entry.get("sha256")
        require(isinstance(digest, str) and HEX_256.fullmatch(digest) is not None,
                f"subjectManifest[{index}] SHA-256 is invalid")
        require(expected_path not in manifest,
                f"subjectManifest duplicates {expected_path}")
        manifest[expected_path] = digest
    return manifest


def historical_lock_object(payload: dict[str, Any]) -> str:
    environment = payload.get("environment")
    require(isinstance(environment, dict), "environment must be an object")
    source_objects = environment.get("sourceObjects")
    require(isinstance(source_objects, dict),
            "environment.sourceObjects must be an object")
    entry = source_objects.get("workspaceLock")
    require(isinstance(entry, dict) and set(entry) == {"path", "gitObject"},
            "workspaceLock source object has unexpected fields")
    require(entry.get("path") == HISTORICAL_ONLY_PATH,
            "workspaceLock source object path drifted")
    object_id = entry.get("gitObject")
    require(isinstance(object_id, str) and GIT_OBJECT.fullmatch(object_id) is not None,
            "workspaceLock source object ID is invalid")
    return object_id


def check_current_applicability(
    artifact_path: Path,
    expected_artifact_sha256: str,
) -> int:
    raw = artifact_path.read_bytes()
    require(HEX_256.fullmatch(expected_artifact_sha256) is not None,
            "expected artifact SHA-256 is invalid")
    require(sha256(raw) == expected_artifact_sha256,
            "benchmark artifact SHA-256 mismatch")
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as error:
        raise ApplicabilityError("benchmark artifact is not JSON") from error
    require(payload.get("schemaVersion") == 1,
            "unsupported benchmark artifact schema")
    require(payload.get("artifactId") == "wcag22-feasibility-admission-raw-v1",
            "unexpected benchmark artifact identity")

    manifest = subject_manifest(payload)
    lock_object = historical_lock_object(payload)
    historical_lock = git_blob(lock_object)
    require(sha256(historical_lock) == manifest[HISTORICAL_ONLY_PATH],
            "historical Cargo.lock blob disagrees with measured subject manifest")

    for path, expected in manifest.items():
        if path == HISTORICAL_ONLY_PATH:
            continue
        current_path = ROOT / path
        require(current_path.is_file(), f"current subject is missing: {path}")
        require(sha256(current_path.read_bytes()) == expected,
                f"current benchmark subject drift: {path}")

    return check_lock_compatibility(historical_lock, (ROOT / "Cargo.lock").read_bytes())


def canonical_lock(records: list[str]) -> bytes:
    header = (
        "# This file is automatically @generated by Cargo.\n"
        "# It is not intended for manual editing.\n"
        "version = 4\n"
    )
    return (header + "".join(f"\n[[package]]\n{record.rstrip()}\n" for record in records)).encode()


def self_test() -> None:
    core = 'name = "labcolors-core"\nversion = "0.2.0"\ndependencies = [\n "dep",\n]'
    dep = (
        'name = "dep"\nversion = "1.0.0"\n'
        'source = "registry+https://example.invalid/index"\n'
        f'checksum = "{"1" * 64}"'
    )
    other = 'name = "other-workspace"\nversion = "0.2.0"'
    historical = canonical_lock([dep, core, other])

    changed_workspace = canonical_lock([
        dep,
        core,
        'name = "other-workspace"\nversion = "0.2.0"\n'
        'dependencies = [\n "labcolors-core",\n]',
        'name = "new-workspace"\nversion = "0.2.0"',
    ])
    require(check_lock_compatibility(historical, changed_workspace) == 2,
            "source-less non-Core workspace drift must remain admissible")

    mutations = {
        "core dependency": canonical_lock([
            dep,
            core.replace(' "dep",', ' "different",'),
            other,
        ]),
        "sourced checksum": canonical_lock([
            dep.replace("1" * 64, "2" * 64), core, other,
        ]),
        "missing sourced package": canonical_lock([core, other]),
        "new sourced package": canonical_lock([
            dep,
            core,
            other,
            'name = "new-dep"\nversion = "1.0.0"\n'
            'source = "registry+https://example.invalid/index"\n'
            f'checksum = "{"3" * 64}"',
        ]),
    }
    for label, mutation in mutations.items():
        try:
            check_lock_compatibility(historical, mutation)
        except ApplicabilityError:
            continue
        raise ApplicabilityError(f"self-test mutation survived: {label}")

    payload = {
        "subjectManifest": [
            {"path": path, "sha256": "0" * 64}
            for path in EXPECTED_SUBJECT_PATHS
        ]
    }
    subject_manifest(payload)
    for label, mutate in {
        "reordered subject": lambda value: value["subjectManifest"].reverse(),
        "missing subject": lambda value: value["subjectManifest"].pop(),
        "extra field": lambda value: value["subjectManifest"][0].update(extra=True),
    }.items():
        candidate = copy.deepcopy(payload)
        mutate(candidate)
        try:
            subject_manifest(candidate)
        except ApplicabilityError:
            continue
        raise ApplicabilityError(f"self-test mutation survived: {label}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("artifact", nargs="?", type=Path)
    parser.add_argument("--artifact-sha256")
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.self_test:
        self_test()
    if args.artifact is None:
        require(args.self_test, "artifact path is required unless --self-test is used")
        print("WCAG22 feasibility applicability self-test: PASS")
        return 0
    require(args.artifact_sha256 is not None,
            "--artifact-sha256 is required for current applicability")
    allowed = check_current_applicability(
        args.artifact.resolve(), args.artifact_sha256
    )
    print(
        "WCAG22 feasibility current applicability: PASS "
        f"historical-lock={HISTORICAL_ONLY_PATH} "
        f"allowed-workspace-record-drift={allowed}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (ApplicabilityError, OSError) as error:
        raise SystemExit(f"WCAG22 feasibility applicability: {error}") from error
